const starterMissionStories = {
  MAKE_LANDFALL: ["You've done it. You've managed to make landfall on an asteroid. It is truly awe-inspiring, and gazing around from the surface takes your breath away. But there's no time to waste. Other Adalians are making their moves and you need to make yours. It's time for you to figure out where you can establish your foothold and leave your mark. Learn how to choose a warehouse location and plan for construction in an empty lot."],
  PROSPECT_THE_SURFACE: ["\"Hey, newbie!\" The older woman called to you from across the Habitat Dining Hall. \"I've got an extra core drill, you can use it,\" she said. After thanking her, she gave you a bit of advice that you took to heart. \"Begin with the end in mind.\" Before you can start digging and mining, you need to know what you are likely to find on a specific lot of land. Prospecting with a core drill will help you to understand what lies beneath the surface, so you can plan your next moves."],
  BEGIN_EXTRACTION: ["Time to start mining! Operating an extractor means you'll be cracking through the surface of an asteroid and pulling up what is buried underneath. All the research you did core sampling will now pay off by turning your discoveries into usable resources and letting them see the light of day."],
  ESTABLISH_STORAGE: ["You discovered that square pegs won't fit into round holes as a toddler. Later, teachers drilled into your head the importance of moving resources from one area to another, of making sure there is a safe place secured to store them before you begin transit. The supply chain is essential to our survival. Now you are ready to put all that theory into practice."],
  REFINE_THE_YIELD: ["\"Psst, hey, kid!\" A man not much older than you are, with wild hair and wilder eyes, is standing right inside the door to your new Refinery. He sends you a proximity message on your Muse with the subject 'The Alchemists' Club' as he walks past you out the door, calling over his shoulder, \"After you learn your basic recipes, get in touch, I'll teach you some REAL transmutations that'll blow your boots off!\" Before you have a chance to ask him how he managed to get inside or what he's talking about, he's gone. Apparently there's a lot to learn about transforming the raw resources you extracted into something new.  "],
  CULTIVATE_LIFE: ["Your stomach rumbles, but it's still an hour until your next meal break. Working in the Bioreactor always makes you hungrier. Something about being so close to the processes for creating food makes you so much more aware of your own body's need for fuel. Still, it's pretty amazing to see how we were able to use what we brought with us from Earth to create a way for humans to live off of these barren rocks."],
  MANUFACTURE_GOODS: ["Ah, the joy of creating something useful. Manufacturing goods for your fellow Adalians gives you a sense of fulfilled purpose. Everything you make will help another human to survive in this harsh landscape. The warm, fuzzy feeling of contentment from consumerism wraps around you like a soft blanket. Not that you can make a soft blanket. That would be a luxury. At least you can make the necessary components for a life support system so that you don't freeze to death in the icy vacuum of space."],
  CLOSE_THE_PRODUCTION_LOOP: ["You've come a long way from starting out at the blank canvas of the surface of an asteroid. You now know what to look for and how to find it, dig it up, transport it, store it, refine it, turn it into food and other useful goods. You're ready to jump into the Marketplace and bask in the glow of success. Here's a bit of extra knowledge to help you on your way."]
};

export default starterMissionStories;
